version: '3'

services:
  # input_grade:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.enterdata
  #   ports:
  #     - "5000:5000"

  # show_results:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.showresults
  #   ports:
  #     - "5001:5001"

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "5002:5002"

  # analytics:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.analytics
  #   ports:
  #     - "5003:5003"

  # mysql_db:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: students_data
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password

  #mongo_db:
  #  image: mongo:latest
  #  container_name: mongo_container
  #  ports:
  #    - "27017:27017"
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: rootadmin
  #    MONGO_INITDB_ROOT_PASSWORD: rootpassword
