# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the input_grade.py file into the container
COPY . /app

# Install Flask and any other needed packages
RUN pip install Flask Flask-MySQLdb

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run the Flask app when the container launches
CMD ["python", "/app/grade_input/input_grade.py"]
