version: '3'

services:
  auth_service:
    build: ./auth_service
    depends_on:
      - mysql
    ports:
      - "5002:5002"
    networks:
      - dumbassnetwork


  login:
    build: ./login
    depends_on:
      - mysql
    ports:
      - "5001:5001"
    networks:
      - dumbassnetwork
  

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: students_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - dumbassnetwork
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

networks:
  dumbassnetwork:
    driver: bridge
