version: '3'

services:
  auth_service:
    build: ./auth_service
    depends_on:
      - mysql
    ports:
      - "5002:5002"
    networks:
      - dumbassnetwork

  login:
    build: ./login
    depends_on:
      - mysql
    ports:
      - "5001:5001"
    networks:
      - dumbassnetwork

  analytics:
    build: ./analytics_service
    depends_on:
      - mysql
      - mongodb
    ports:
      - "5003:5003"
    networks:
      - dumbassnetwork

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: students_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - dumbassnetwork
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootadmin
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    networks:
      - dumbassnetwork
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d

networks:
  dumbassnetwork:
    driver: bridge
