apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      hostname: mongodb
      containers:
      - name: mongodb
        image: churu/mongodb:latest
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: rootadmin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: rootpassword
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30007

