apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-results-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: show-results-service
  template:
    metadata:
      labels:
        app: show-results-service
    spec:
      containers:
      - name: login-service
        image: churu/acit-3495-project2-show-results:latest
        ports:
        - containerPort: 5004        
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
